### ISSUE TITLE
Error when relaunching AutoClicker

### ISSUE THREAD

**Issue by ascpial** [ExplodingBottle/AutoClicker2000#1]
I have use the AutoClicker 200 to do CPS test, but when I stop and restart the program, it crash

Error message 
```Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\----\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\-----\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\-----\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "C:\Users\-----\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\__init__.py", line 213, in pre_process_event
    key_hook(event)
  File "C:\Users\-----\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\__init__.py", line 510, in <lambda>
    return hook_key(key, lambda e: e.event_type == KEY_UP or callback(e), suppress=suppress)
  File "C:\Users\------\AutoClicker.py", line 54, in tryLc
    lcThreadOb.start()
  File "C:\Users\-----\AppData\Local\Programs\Python\Python39\lib\threading.py", line 869, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once```

**Comment by ExplodingBottle** [comment]
Thanks for the report,
I have fixed your issue in the new release,
https://github.com/ExplodingBottle/AutoClicker2000/releases/tag/v1.0-clean

Thanks you.
